name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: icepyromaniac/truthbeetold
        registry: docker.io
        dockerfile: /server/
        directory: /server/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
